### ISSUE TITLE
File produces 3GB file

### ISSUE THREAD

**Issue by kongo86** [mandiant/GoReSym#69]
Hi Team, 

The following file: `1185fa967aa989d5e072577e493d2b307c48181480129d4c45337da64d5bfd25`
When running goresym.exe (hash: 6d8c532702bd33adae0bf25e1717a441531369e86350dbb0db2d5d717a0c926a) with the following params:
`
GoReSym.exe -t -d -p .\1185fa967aa989d5e072577e493d2b307c48181480129d4c45337da64d5bfd25 > 1185fa_goresym`

![image](https://github.com/user-attachments/assets/25f2210c-c2e8-48b8-9565-b274422d6bbe)

**Comment by stevemk14ebr** [comment]
The symbol recovery appears to be correct. Your binary contains function names that are intentionally huge and obfuscated. Example of the name of the first function in the `ftab`:

![image](https://github.com/user-attachments/assets/fce68102-0993-48fa-abec-711af584d321)

the moduledata pointing to the ftab:
![image](https://github.com/user-attachments/assets/a56ac5e4-9e00-4a1b-8ded-510b42e6440c)

GoReSym can only recover what is present and someone has stomped your symbols with huge names which is why the output is so large.
